import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { FielDocumentComponent } from '../fiel-document/fiel-document.component';
import { loadFielDocument } from '../fiel-document/fiel-document.loader';
import { FielDocument, FielPage } from '../fiel-document/fiel-document.model';

// Any folder generated by gem_json.py under public/demo (see demo/index.json).
// const DEMO_JSON = 'demo/fondo-deskewed/document.json';
// const DEMO_JSON = 'demo/civil-register/document.json';
const DEMO_JSON = 'demo/camilo-passport/document.json';

@Component({
  selector: 'app-review-page',
  imports: [FielDocumentComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (doc(); as d) {
      <div class="actions">
        <button type="button" (click)="download(d)">Download reviewed JSON</button>
      </div>
      @for (page of d.pages; track page.page_number; let i = $index) {
        @if (d.pages.length > 1) {
          <h2 class="page-label">Page {{ page.page_number }} of {{ d.pages.length }}</h2>
        }
        <fiel-document [document]="page" (documentChange)="updatePage(i, $event)" />
      }
    } @else if (error()) {
      <p class="error">{{ error() }}</p>
    } @else {
      <p>Loading document…</p>
    }
  `,
  styles: `
    .actions { display: flex; justify-content: flex-end; padding: 8px 16px; }
    .page-label { margin: 24px 16px 0; font-size: 13px; text-transform: uppercase; letter-spacing: .06em; color: #52525b; }
    .error { color: #b91c1c; padding: 16px; }
  `,
})
export class ReviewPage {
  readonly doc = signal<FielDocument | null>(null);
  readonly error = signal<string | null>(null);

  constructor() {
    loadFielDocument(DEMO_JSON)
      .then(doc => this.doc.set(doc))
      .catch((e: Error) => this.error.set(e.message));
  }

  updatePage(index: number, page: FielPage): void {
    this.doc.update(doc => (doc ? { ...doc, pages: doc.pages.map((p, i) => (i === index ? page : p)) } : doc));
  }

  download(doc: FielDocument): void {
    const blob = new Blob([JSON.stringify(doc, null, 2)], { type: 'application/json' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = 'document.reviewed.json';
    link.click();
    URL.revokeObjectURL(link.href);
  }
}
